### ISSUE TITLE
SoapUI 5.5.0: Upgrade of 'json-path-0.9.1.jar' lib

### ISSUE THREAD

**Issue by cwirek91** [SmartBear/soapui#461]
When I upgrade the lib from v0.9.1 to any newer version i receive an error in JsonPath assertions:

ERROR [SoapUI] An error occurred [com/jayway/jsonpath/spi/JsonProvider], see error log for details

2019-04-06 23:25:05,015 ERROR [errorlog] java.lang.NoClassDefFoundError: com/jayway/jsonpath/spi/JsonProvider java.lang.NoClassDefFoundError: com/jayway/jsonpath/spi/JsonProvider

SoapUI is looking for JsonProvider.class in \com\jayway\jsonpath\spi\ path, but newer versions (0.9.1+) have this class in \com\jayway\jsonpath\spi\json\

Is it possible to fix this?

**Comment by IlyaAvdeev** [comment]
Hi, @cwirek91, what root issue did you try to address?

**Comment by Aracaa** [comment]
I think the main point is to update dependencies json-path from 0.9.1 to latest version. 
json-path 0.9.1 has been released 7 years ago, and current version is 2.4.0

`soapui` module doesn't compile with json-path 1.0.0 because lib has been refactored (PathTokenizer doesn't exists anymore).

Make this update will helps to use either Soapui or ReadyAPI for JsonPath assertion

However, assert may change with this new lib version 
[Doc from ReadyApi](https://support.smartbear.com/readyapi/docs/testing/jsonpath-reference.html#_ga=2.98663966.1657263003.1591185664-228511478.1575447692)
[JsonPath github](https://github.com/json-path/JsonPath)

**Comment by antone-sb** [comment]
Fixed in 5.7.0.
